//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StatusCodeMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public StatusCodeMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Messages.StatusCodeMessages", typeof(StatusCodeMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cache is empty. Please ensure data is loaded..
        /// </summary>
        public static string CacheEmpty {
            get {
                return ResourceManager.GetString("CacheEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The request was successful..
        /// </summary>
        public static string Status200SuccessfulRequest {
            get {
                return ResourceManager.GetString("Status200SuccessfulRequest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The request has been fulfilled and resulted in a new resource being created..
        /// </summary>
        public static string Status201Created {
            get {
                return ResourceManager.GetString("Status201Created", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The server successfully processed the request and there is no additional content to send..
        /// </summary>
        public static string Status204NoContent {
            get {
                return ResourceManager.GetString("Status204NoContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The server could not understand the request due to invalid syntax..
        /// </summary>
        public static string Status400BadRequest {
            get {
                return ResourceManager.GetString("Status400BadRequest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User not authenticated correctly..
        /// </summary>
        public static string Status401Unauthorized {
            get {
                return ResourceManager.GetString("Status401Unauthorized", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The user does not have permission to perform this operation..
        /// </summary>
        public static string Status403Forbidden {
            get {
                return ResourceManager.GetString("Status403Forbidden", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The requested resource could not be found..
        /// </summary>
        public static string Status404NotFound {
            get {
                return ResourceManager.GetString("Status404NotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The request could not be completed due to a conflict with the current state of the target resource..
        /// </summary>
        public static string Status409Conflict {
            get {
                return ResourceManager.GetString("Status409Conflict", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred..
        /// </summary>
        public static string Status500InternalServerError {
            get {
                return ResourceManager.GetString("Status500InternalServerError", resourceCulture);
            }
        }
    }
}
